In [2]:
import pandas as pd
import numpy as np

np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [3]:
import numpy as np
arr = np.arange(1,17).reshape(4,4)
print("array:\n", arr)
first_row = arr[0]
print("first row:\n", first_row)
last_column = arr[:, -1]
print("last column:\n", last_column)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
first row:
 [1 2 3 4]
last column:
 [ 4  8 12 16]


In [43]:
import numpy as np
identity_= np.eye(4)
print(identity_)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
import numpy as np
#original array
samplearray = np.array([[3, 6, 9, 12],
                       [15, 18, 21, 24],
                       [27, 30, 33, 36], 
                       [39, 42, 45, 48]])

#using slicing to select odd rows and even columns
#the slice [1::2] selects every second element starting from index 1 (odd rows)
#the slice [0::2] selects every second element starting from index 0 (even columns)
newArray = samplearray[1::2, 0::2]
print("Original array:")
print(samplearray)
print("\nNew array with odd rows and even columns:")
print(newArray)


Original array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]]

New array with odd rows and even columns:
[[15 21]
 [39 45]]


In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\python-library\\data.csv", encoding='latin1')
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        1

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom


In [8]:
df.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom


In [9]:
import numpy as np
import pandas as pd

arr = np.array([2,5,7,10,12,15])
result = arr[(arr >= 5) & (arr <= 10)]

In [10]:
import numpy as np
import pandas as pd
 
arr = np.random.randint(1, 100, size=(3, 2))
print("matrix:\n", arr)
print("maximum value:", arr.max())
print("minimum value:", arr.min())

matrix:
 [[97 32]
 [74 64]
 [69 55]]
maximum value: 97
minimum value: 32


In [11]:
import numpy as np
import pandas as pd
 
arr = np.random.randint(1, 100, size=(3, 2))
print("matrix:\n", arr)
print("maximum value:", arr.max())
print("minimum value:", arr.min())

matrix:
 [[53 77]
 [89 13]
 [ 4 75]]
maximum value: 89
minimum value: 4


In [12]:
import numpy as np

samplearray = np.array([[34, 43, 73],
                        [82, 22, 12],
                        [53, 94, 66]])

newColumnAdd = np.array([10, 10, 10])

# Delete second column (index 1)
arr = np.delete(samplearray, 1, axis=1)

# Insert new column at index 1
arr = np.insert(arr, 1, newColumnAdd, axis=1)

print(arr)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [13]:
import numpy as np
import pandas as pd
arr = np.random.randint(1,101,10)
print(arr)

[ 57  83  97  24  35 100  10  50  39  83]


In [14]:
import numpy as np

arr = np.random.randint(1, 100, (3, 3))

print("Original Array:")
print(arr)

sorted_arr = np.sort(arr, axis=1)

print("Row-wise Sorted Array:")
print(sorted_arr)

Original Array:
[[43 80 73]
 [34  6 31]
 [68 56 70]]
Row-wise Sorted Array:
[[43 73 80]
 [ 6 31 34]
 [56 68 70]]


In [15]:
import numpy as np

arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])

result = arr[arr[:, 1].argsort()]

print(result)

[[5 2 7]
 [8 4 1]
 [6 9 3]]


In [11]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom


In [12]:
# 2. DATA CLEANING
df = df.dropna(subset=["CustomerID"])
print("shape of the dataframe after dropping rows with missing CustomerID:", df.shape)

shape of the dataframe after dropping rows with missing CustomerID: (406829, 8)


In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    406829 non-null  object 
 1   StockCode    406829 non-null  object 
 2   Description  406829 non-null  object 
 3   Quantity     406829 non-null  int64  
 4   InvoiceDate  406829 non-null  object 
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 27.9+ MB


In [24]:
print("Shape (rows, cols:)",df.shape)

Shape (rows, cols:) (406829, 8)


In [25]:
#check missing values using isnull()
print("\nColumn-wise missing values \n",df.isnull().sum())


Column-wise missing values 
 InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64


In [27]:
#gives the statistical summary of the data
df.describe()

,Quantity,UnitPrice,CustomerID
count,406829.000000,406829.000000,406829.000000
mean,12.061303,3.460471,15287.690570
std,248.693370,69.315162,1713.600303
min,-80995.000000,0.000000,12346.000000
25%,2.000000,1.250000,13953.000000
50%,5.000000,1.950000,15152.000000
75%,12.000000,3.750000,16791.000000
max,80995.000000,38970.000000,18287.000000


In [40]:
# Drop rows with missing Description and keep a clean copy
if df is not None and "Description" in df.columns:
    df = df.dropna(subset=["Description"]).copy()
else:
    print("DataFrame is missing or the 'Description' column is not available.")

DataFrame is missing or the 'Description' column is not available.


In [26]:
df.duplicated().sum()

np.int64(5225)

In [15]:
print(df.shape)

(406829, 8)


In [19]:
df_cleaned = df.drop_duplicates()
print("shape of the dataframe after dropping duplicates:", df_cleaned.shape)

shape of the dataframe after dropping duplicates: (401604, 8)


In [20]:
df_clean= df_cleaned[df_cleaned['Quantity'] > 0]

In [23]:
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

C:\Users\sanch\AppData\Local\Temp\ipykernel_17120\2779893561.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])


In [21]:
df_clean["TotalPrice"] = np.multiply(df_clean["Quantity"], df_clean["UnitPrice"])

C:\Users\sanch\AppData\Local\Temp\ipykernel_17120\3436313488.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["TotalPrice"] = np.multiply(df_clean["Quantity"], df_clean["UnitPrice"])


In [22]:
df_clean["TotalPrice"]

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...  
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 392732, dtype: float64

In [39]:
print("Step 3: Data Cleaning")
print("Original rows in the dataset:", df.shape[0] if df is not None else 0)
print("cancelled orders removed:", int(df["iscancelled"].sum()) if df is not None and "iscancelled" in df.columns else 0)
print("rows after cleaning:", df_clean.shape[0] if 'df_clean' in locals() else 0)
print(df_clean[["InvoiceNo", "Description", "Quantity", "UnitPrice", "CustomerID", "InvoiceDate", "TotalPrice"]].head(10) if 'df_clean' in locals() else "No cleaned dataset available")
print("\n")

Step 3: Data Cleaning
Original rows in the dataset: 0
cancelled orders removed: 0
rows after cleaning: 392732
  InvoiceNo                          Description  Quantity  UnitPrice  \
0    536365   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55   
1    536365                  WHITE METAL LANTERN         6       3.39   
2    536365       CREAM CUPID HEARTS COAT HANGER         8       2.75   
3    536365  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39   
4    536365       RED WOOLLY HOTTIE WHITE HEART.         6       3.39   
5    536365         SET 7 BABUSHKA NESTING BOXES         2       7.65   
6    536365    GLASS STAR FROSTED T-LIGHT HOLDER         6       4.25   
7    536366               HAND WARMER UNION JACK         6       1.85   
8    536366            HAND WARMER RED POLKA DOT         6       1.85   
9    536367        ASSORTED COLOUR BIRD ORNAMENT        32       1.69   

   CustomerID         InvoiceDate  TotalPrice  
0     17850.0 2010-12-01 08:26:00     

In [37]:
#Extract the year, month, and day from the InvoiceDate column and store them in new columns in the dataframe 

df_clean["year"]= df_clean["InvoiceDate"].dt.year

df_clean["month"]= df_clean["InvoiceDate"].dt.month

df_clean["day"]= df_clean["InvoiceDate"].dt.day


# Extra
df_clean["hour"] = df_clean["InvoiceDate"].dt.hour

# extract the name of the day of the week.
df_clean["day_of_week"] = df_clean["InvoiceDate"].dt.day_name()

C:\Users\sanch\AppData\Local\Temp\ipykernel_17120\963633600.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["year"]= df_clean["InvoiceDate"].dt.year
C:\Users\sanch\AppData\Local\Temp\ipykernel_17120\963633600.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["month"]= df_clean["InvoiceDate"].dt.month
C:\Users\sanch\AppData\Local\Temp\ipykernel_17120\963633600.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,c

In [42]:
print("step 4: Data feature added")
print(df_clean[["InvoiceNo", "year", "month", "day_of_week", "hour"]].head(10) )
print("\n")

step 4: Data feature added
  InvoiceNo  year  month day_of_week  hour
0    536365  2010     12   Wednesday     8
1    536365  2010     12   Wednesday     8
2    536365  2010     12   Wednesday     8
3    536365  2010     12   Wednesday     8
4    536365  2010     12   Wednesday     8
5    536365  2010     12   Wednesday     8
6    536365  2010     12   Wednesday     8
7    536366  2010     12   Wednesday     8
8    536366  2010     12   Wednesday     8
9    536367  2010     12   Wednesday     8




In [2]:
import numpy as np

In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path

# STEP 5: Compute business metrics

# NUNIQUE: Count the number of unique customers, orders, and products
# if an invoice has multiple products, it will be counted as one order
total_revenue = np.sum(df_clean['TotalPrice'])
total_orders = df_clean['InvoiceNo'].nunique()
total_customers = df_clean['CustomerID'].nunique()
avg_order_value= df_clean.groupby('InvoiceNo')['TotalPrice'].sum().mean()

print('total_revenue:', total_revenue)
print('total_orders:', total_orders)
print('total_customers:', total_customers)
print('average_order_value:', avg_order_value)


total_revenue: 8887208.894
total_orders: 18536
total_customers: 4339
average_order_value: 479.45667317652135


STEP 6: TOP Products (by revenue and by quantity )

In [ ]:
# find the top 10 products that generated the highest total revenue
top_products_revenue = (df_clean.groupby("Description")['TotalPrice'].sum().sort_values(ascending=False).head(10))


# find the top 10 products that were sold in the highest quantity
top_products_quantity = (df_clean.groupby("Description")['Quantity'].sum().sort_values(ascending=False).head(10))

In [12]:
# Display the results

print("step 6: Top 10 products by revenue")
print(top_products_revenue)
print("\nTop 10 products by quantity sold")
print(top_products_quantity)
print("\n")

step 6: Top 10 products by revenue
Description
PAPER CRAFT , LITTLE BIRDIE           168469.60
REGENCY CAKESTAND 3 TIER              142264.75
WHITE HANGING HEART T-LIGHT HOLDER    100392.10
JUMBO BAG RED RETROSPOT                85040.54
MEDIUM CERAMIC TOP STORAGE JAR         81416.73
POSTAGE                                77803.96
PARTY BUNTING                          68785.23
ASSORTED COLOUR BIRD ORNAMENT          56413.03
Manual                                 53419.93
RABBIT NIGHT LIGHT                     51251.24
Name: TotalPrice, dtype: float64

Top 10 products by quantity sold
Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        77916
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54319
JUMBO BAG RED RETROSPOT               46078
WHITE HANGING HEART T-LIGHT HOLDER    36706
ASSORTED COLOUR BIRD ORNAMENT         35263
PACK OF 72 RETROSPOT CAKE CASES       33670
POPCORN HOLDER                        30919
RABBIT NIGHT LIGHT                    2715

Step 7: Country-Wise Analysis

In [13]:
# Calculate the total revenue generated by each country and sort it from highest to lowest.

country_revenue = (df_clean.groupby("Country")['TotalPrice']
                   .sum().astype(int).sort_values(ascending=False)) 

In [15]:
# Display the results
print("step 7: Total revenue by country")
print(country_revenue.head(10))  # Display only the top 10 countries by revenue

step 7: Total revenue by country
Country
United Kingdom    7285024
Netherlands        285446
EIRE               265262
Germany            228678
France             208934
Australia          138453
Spain               61558
Switzerland         56443
Belgium             41196
Sweden              38367
Name: TotalPrice, dtype: int64


STEP 8: Monthly sales trend

In [19]:
# Create a new column containing only the year and month from the InvoiceDate column. This will help us analyze the sales trends over time on a monthly basis.
df_clean["yearMonth"] = df_clean["InvoiceDate"].dt.to_period("M")

# Calculate the total sales(revenue) for each year-Month
monthly_sales = df_clean.groupby("yearMonth")['TotalPrice'].sum()

print("step 8: Monthly sales trends")
print(monthly_sales)  # Display only the first 10 months of sales trends   

step 8: Monthly sales trends
yearMonth
2010-12     570422.730
2011-01     568101.310
2011-02     446084.920
2011-03     594081.760
2011-04     468374.331
2011-05     677355.150
2011-06     660046.050
2011-07     598962.901
2011-08     644051.040
2011-09     950690.202
2011-10    1035642.450
2011-11    1156205.610
2011-12     517190.440
Freq: M, Name: TotalPrice, dtype: float64


In [23]:
df_clean["weekMonth"] = df_clean["InvoiceDate"].dt.to_period("W")
print("step 10: Sales by week")
print(df_clean.groupby("weekMonth")['TotalPrice'].sum())

step 10: Sales by week
weekMonth
2010-11-29/2010-12-05    148627.970
2010-12-06/2010-12-12    212619.130
2010-12-13/2010-12-19    163116.120
2010-12-20/2010-12-26     46059.510
2011-01-03/2011-01-09    114636.800
2011-01-10/2011-01-16    154344.850
2011-01-17/2011-01-23    175452.230
2011-01-24/2011-01-30    104861.000
2011-01-31/2011-02-06    105955.810
2011-02-07/2011-02-13     87827.940
2011-02-14/2011-02-20    125700.150
2011-02-21/2011-02-27    130380.770
2011-02-28/2011-03-06    117386.820
2011-03-07/2011-03-13    112193.930
2011-03-14/2011-03-20    137669.820
2011-03-21/2011-03-27    129560.720
2011-03-28/2011-04-03    143657.580
2011-04-04/2011-04-10    119697.730
2011-04-11/2011-04-17    134930.821
2011-04-18/2011-04-24    115969.400
2011-04-25/2011-05-01     73374.060
2011-05-02/2011-05-08    131094.120
2011-05-09/2011-05-15    178574.320
2011-05-16/2011-05-22    195818.790
2011-05-23/2011-05-29    146776.610
2011-05-30/2011-06-05    102040.370
2011-06-06/2011-06-12    193704

In [25]:
df_clean["Dayweek"] = df_clean["InvoiceDate"].dt.to_period("D")
print("step 11: Sales by day")
print(df_clean.groupby("Dayweek")['TotalPrice'].sum())


step 11: Sales by day
Dayweek
2010-12-01     46192.49
2010-12-02     47197.57
2010-12-03     23876.63
2010-12-05     31361.28
2010-12-06     31009.33
                ...    
2011-12-05     58081.09
2011-12-06     45989.66
2011-12-07     69230.60
2011-12-08     50395.96
2011-12-09    184329.66
Freq: D, Name: TotalPrice, Length: 305, dtype: float64


Step 9: Customer Anlaysis (RFM-Style basics)

In [ ]:
# create a customer summary by calculating spending, number of orders, average order value, and last purchase date for each customer. This will help us understand the purchasing behavior of our customers.
customer_summary = (
    df_clean.groupby("CustomerID")
    .agg(
        totalSpent=("TotalPrice", "sum"),
        NumOrders=("InvoiceNo", "nunique"),
        AvgOrderValue=("TotalPrice", "mean"),
        LastPurchase=("InvoiceDate", "max"),
    )
    .sort_values("totalSpent", ascending=False)
)

customer_summary.head()

,totalSpent,NumOrders,AvgOrderValue,LastPurchase
CustomerID,,,,
14646.0,280206.02,74,134.714433,2011-12-08 12:12:00
18102.0,259657.30,60,602.453132,2011-12-09 11:50:00
17450.0,194390.79,46,578.544018,2011-12-01 13:29:00
16446.0,168472.50,2,56157.500000,2011-12-09 09:15:00
14911.0,143711.17,201,25.336948,2011-12-08 15:54:00


STEP 10: Numpy-based statistical analysis on order values


In [28]:
# calculate the total value of each order (invoice) and store the results as a numpy array.

order_values= df_clean.groupby("InvoiceNo")["TotalPrice"].sum().values

order_values

array([139.12,  22.2 , 278.73, ..., 329.05, 339.2 , 249.45],
      shape=(18536,))

In [32]:
# Step 10: calculate and display basic statistics for orders values.
print("step 10: order value statistics (Numpy)")

# Display the average order value
print("Mean:", np.mean(order_values))

# Display the middle (median) order value
print("Median:", np.median(order_values))

# Display the spread of order values
print("Standard Deviation:", np.std(order_values))

# Display the smallest order value
print("Minimum:", np.min(order_values))

# Display the largest order value
print("Maximum:", np.max(order_values))


# Display the range of order values
print("Range:", np.ptp(order_values))


step 10: order value statistics (Numpy)
Mean: 479.45667317652135
Median: 302.565
Standard Deviation: 1677.8710230951103
Minimum: 0.0
Maximum: 168469.6
Range: 168469.6


Step 11: Save Cleaned data & summary outputs

In [33]:
# save the cleaned dataset to a new CSV file without including the row index.

df_clean.to_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\python-library\\cleaned_data.csv", index=False)

# Save the customer summary report to a csv file.
customer_summary.to_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\python-library\\customer_summary.csv", index=True)

# save the country- wise revenue report to a csv file.
country_revenue.to_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\python-library\\country_revenue.csv", index=True)